---
- block:

  - name: ({{ notes }}) backup old output file
    copy:
      backup: yes
      content: ""
      dest: "{{ output_file }}"
      force: yes

  - name: ({{ notes }}) run workload dependent pre-conditioning on {{ device_node_name }}
    become: yes
    command: >
      {{ fio_dir }}/fio {{ pre_conditioning_job_filename }} --offset={{ io_offset }}
      --output-format={{ output_format }}
      --output {{ output_file }}
    args:
      chdir: "{{ workdir }}"

  - name: ({{ notes }}) get throughput in kbytes per second
    # See the difference between bw and bw_mean
    # http://maillist.kernel.dk/fio-devel/0054.html
    shell: cat {{ output_file }} | {{ workdir }}/jq '{{ value_key_prefix }}.bw'
    register: comm_res

  - debug:
      msg: "throughput: {{ comm_res.stdout }} KB/s"
      verbosity: "{{ verbosity }}"

  - name: ({{ notes }}) save throughput for steady state detection
    set_fact:
      # convert from KB/s to MB/s before adding to the list
      tracking_values: >
        {{ tracking_values + [ comm_res.stdout | float / 1024 ] }}

  - debug:
      msg: "current throughput values (MB/s): {{ tracking_values }}"
      verbosity: "{{ verbosity }}"

  - name: ({{ notes }}) check steady state
    command: >
      {{ role_path }}/files/verify_ss.py '{{ tracking_values }}' {{ measurement_window_size }}
    register: comm_res
    ignore_errors: yes

  - name: ({{ notes }}) update loop condition
    set_fact:
      steady_state: "{{ True if comm_res.rc == 0 else False }}"

  - name: ({{ notes }}) get total performed IO in bytes
    shell: cat {{ output_file }} | {{ workdir }}/jq '{{ value_key_prefix }}.io_bytes'
    register: comm_res
    when: not steady_state

  - debug:
      msg: "total IO performed: {{ comm_res.stdout }} bytes"
      verbosity: "{{ verbosity }}"

  - name: ({{ notes }}) update offset for next round
    set_fact:
      io_offset: >
        {% set offset_num = io_offset | int + comm_res.stdout | int -%}
        {% set size_of_range = (device_size | int * active_range / 100) | int -%}
        {% if offset_num >= size_of_range -%}
          {% set offset_num = offset_num - size_of_range -%}
        {% endif -%}
        {{ offset_num }}
    when: not steady_state

  when: not steady_state
...
