---
- set_fact:
    json_key_path: .jobs.{{ 'read' if rwmixread == 100 else 'write' }}
    throughputs_in_windows: []  # the item value is in the unit of MB/s

- include_tasks: tmp_job_files.yml

- include_tasks: do_until_steady_state.yml
  vars:
    notes: "bs {{ block_size }}, %read {{ rwmixread }}, round {{ cur_round }}"
  with_sequence: count=25
  loop_control:
    loop_var: cur_round

- set_fact: steady_state=False
...
