---
- set_fact:
    notes: "bs {{ block_size }}"

- include_tasks: tmp_job_files.yml
  vars:
    io_pattern: write
    included_job_file: wipc.fio

- name: ({{ notes }}) check and kill remnant pre-conditioning process
  become: yes
  shell: pkill -KILL -u "$(id -u)" -f 'fio\s+pre\-conditioning\.fio'
  ignore_errors: yes

- name: ({{ notes }}) run workload independent pre-conditioning on {{ device_node_name }}
  become: yes
  command: >
    fio-fio-{{ fio_version }}/fio {{ pre_conditioning_job_file }}
    --output {{ output_dir }}/wipc_{{ block_size }}.txt
  args:
    chdir: "{{ workdir }}"

- include_tasks: loop_rw_mix.yml
  vars:
    included_job_file: wdpc.fio
  with_items:
    - read
    - write
  loop_control:
    loop_var: io_pattern
...
