---
- name: ({{ notes }}) backup local output file
  local_action:
    module: copy
    backup: yes
    content: ""
    dest: "{{ local_output_file }}"
    force: yes
    owner: "{{ lookup('env', 'USER') }}"

- name: ({{ notes }}) fetch remote output file
  fetch:
    dest: "{{ local_output_file }}"
    fail_on_missing: yes
    flat: yes
    src: "{{ remote_output_file }}"
...
