---
- include_tasks: tmp_job_files.yml
  vars:
    included_job_filename: wipc.fio
    io_pattern: write

- name: ({{ notes }}) backup old output file
  copy:
    backup: yes
    content: ""
    dest: "{{ output_file }}"
    force: yes

- name: ({{ notes }}) run workload independent pre-conditioning on {{ device_node_name }}
  become: yes
  command: >
    {{ fio_dir }}/fio {{ pre_conditioning_job_filename }}
    --output-format={{ output_format }}
    --output {{ output_file }}
  args:
    chdir: "{{ workdir }}"

- include_tasks: tmp_job_files.yml
  vars:
    included_job_filename: wdpc.fio
    io_pattern: readwrite

- set_fact:
    job_key_path: .jobs[0].{{ 'read' if rwmixread == 100 else 'write' }}
    io_offset: 0
    throughputs_values: []
    steady_state: False
    outer_notes_rw_mix: "{{ notes }}"

- include_tasks: do_until_steady_state.yml
  vars:
    notes: "{{ outer_notes_rw_mix }}, round {{ cur_round }}"
    output_file: "{{ output_dir }}/wdpc_bs{{ block_size }}_read{{ rwmixread }}_round{{ cur_round }}.{{ output_file_suffix }}"
  with_sequence: count=25
  loop_control:
    loop_var: cur_round

- name: ({{ notes }}) print final steady state
  debug:
    var: steady_state
...
