---
- include_tasks: tmp_job_files.yml
  vars:
    included_job_filename: wdpc.fio
    io_pattern: "{{ wdpc_io_pattern }}"
    bssplit: "{{ cur_bssplit }}"

- set_fact:
    tracking_values: []
    steady_state: False
    outer_notes_rw_mix: "{{ notes }}"

- include_tasks: do_until_steady_state.yml
  vars:
    notes: "{{ outer_notes_rw_mix }}, round {{ cur_round }}"
    output_filename: "wdpc_bs{{ cur_bssplit | replace('/', '-') }}_read{{ cur_rwmixread }}_round{{ cur_round }}.{{ output_file_suffix }}"
  loop: "{{ range(1, maximum_rounds + 1) | list }}"
  loop_control:
    loop_var: cur_round

- name: ({{ notes }}) print final steady state
  debug:
    var: steady_state
...
