---
- block:
    - name: ({{ notes }}) discard sectors for device {{ device_node_name }}
      become: yes
      command: >
        {{ remote_scripts_dir }}/{{ discard_sectors_script_filename }}
        {{ device_node_name }}

    - include_tasks: tmp_job_files.yml
      vars:
        included_job_filename: wipc.fio
        io_pattern: write
        bssplit: "{{ wipc_bssplit }}"

    - name: ({{ notes }}) run workload independent pre-conditioning on {{ device_node_name }}
      become: yes
      command: >
        {{ fio_command_prefix }} {{ fio_dir }}/fio {{ pre_conditioning_job_file }}
        --output-format={{ output_format }}
        --output {{ remote_output_file }}

    - include_tasks: backup_output_file.yml
  when: run_wipc

- meta: end_play
  when: run_wipc_only

- name: update parameters
  set_fact:
    run_wipc: "{{ not run_wipc_once }}"

    # save the outer notes.
    outer_notes_block_sizes: "{{ notes }}"

- include_tasks: loop_rw_mix.yml
  vars:
    notes: "{{ outer_notes_block_sizes }}, %read {{ cur_rwmixread }}"
  loop: "{{ rwmixreads }}"
  loop_control:
    loop_var: cur_rwmixread
...
