---
- include_tasks: tmp_job_files.yml
  vars:
    included_job_filename: wipc.fio
    io_pattern: write
    block_size: "{{ wipc_block_size }}"

- name: ({{ notes }}) backup old output file
  copy:
    backup: yes
    content: ""
    dest: "{{ output_file }}"
    force: yes

- name: ({{ notes }}) run workload independent pre-conditioning on {{ device_node_name }}
  become: yes
  command: >
    {{ fio_dir }}/fio {{ pre_conditioning_job_filename }}
    --output-format={{ output_format }}
    --output {{ output_file }}
  args:
    chdir: "{{ workdir }}"

- include_tasks: tmp_job_files.yml
  vars:
    included_job_filename: wdpc.fio
    io_pattern: "{{ wdpc_io_pattern }}"
    block_size: "{{ cur_block_size }}"

- include_tasks: ss_reset.yml

- set_fact:
    value_key_prefix: jobs[0].{{ key_prefix_in_job }}.
    tracking_values: []
    steady_state: False
    outer_notes_rw_mix: "{{ notes }}"

- include_tasks: do_until_steady_state.yml
  vars:
    notes: "{{ outer_notes_rw_mix }}, round {{ cur_round }}"
    output_file: "{{ output_dir }}/wdpc_bs{{ cur_block_size }}_read{{ cur_rwmixread }}_round{{ cur_round }}.{{ output_file_suffix }}"
  with_sequence: count=25
  loop_control:
    loop_var: cur_round

- name: ({{ notes }}) print final steady state
  debug:
    var: steady_state
...
