---
- name: ensure the presence of remote output dir {{ remote_output_dir }}
  file:
    path: "{{ remote_output_dir }}"
    state: directory

- name: ensure the presence of local output dir {{ local_output_dir }}
  local_action:
    module: file
    path: "{{ local_output_dir }}"
    state: directory

- name: load specific test variables
  include_vars:
    dir: .
    files_matching: "{{ test_spec }}.yml"

- set_fact:
    run_wipc: "{{ not skip_first_wipc }}"

- include_tasks: loop_block_sizes.yml
  vars:
    notes: "bs {{ cur_block_size }}"
    output_filename: "wipc_bs{{ cur_block_size }}.{{ output_file_suffix }}"
    remote_output_file: "{{ remote_output_dir }}/{{ output_filename }}"
    local_output_file: "{{ local_output_dir }}/{{ output_filename }}"
  with_items: "{{ block_sizes }}"
  loop_control:
    loop_var: cur_block_size
...
