---
- name: ensure the presence of remote output dir {{ remote_output_dir }}
  file:
    path: "{{ remote_output_dir }}"
    state: directory

- name: ensure the presence of local output dir {{ local_output_dir }}
  local_action:
    module: file
    path: "{{ local_output_dir }}"
    state: directory

- name: load specific test variables
  include_vars:
    dir: .
    files_matching: "{{ test_spec }}.yml"

- include_tasks: loop_block_sizes.yml
  vars:
    notes: "bs {{ cur_block_size }}"
  with_items: "{{ block_sizes }}"
  loop_control:
    loop_var: cur_block_size
...
