---
- name: ({{ notes }}) template the pre-conditioning job file to {{ remote_job_files_dir }}
  template:
    backup: yes
    dest: "{{ pre_conditioning_job_file }}"
    force: yes
    src: "{{ pre_conditioning_job_filename }}"

- name: ({{ notes }}) template the included job file to {{ remote_job_files_dir }}
  template:
    backup: yes
    dest: "{{ remote_job_files_dir }}/{{ included_job_filename }}"
    force: yes
    src: "{{ included_job_filename }}"
...
