---
# See SSS PTS v2.0.1 on page 36
# https://www.snia.org/sites/default/files/technical_work/PTS/SSS_PTS_2.0.1.pdf
thread_count: 1
queue_depth: 32

wipc_block_size: "{{ cur_block_size }}"
wdpc_io_pattern: readwrite

block_sizes: ['4KB', '8KB', '16KB', '32KB', '128KB', '1024KB']
rwmixreads: [100, 0]
