---
- block:

  - name: ({{ notes }}) run workload dependent pre-conditioning on {{ device_node_name }}
    become: yes
    command: >
      {{ fio_dir }}/fio {{ pre_conditioning_job_file }}
      --output-format={{ output_format }}
      --output {{ remote_output_file }}

  - include_tasks: backup_output_file.yml

  - include_tasks: save_value.yml

  - name: ({{ notes }}) check steady state
    script: >
      {{ role_path }}/files/verify_ss.py '{{ tracking_values }}' {{ measurement_window_size }}
    register: comm_res
    ignore_errors: yes

  - name: ({{ notes }}) update loop condition
    set_fact:
      steady_state: "{{ True if comm_res.rc == 0 else False }}"

  when: not steady_state
...
