---
- hosts: all
  any_errors_fatal: true
  tags: [ 'always' ]
  vars:
    yeses: ["yes", "y"]
  tasks:
    - set_fact:
        device_node_name: "/dev/{{ device_name }}"
    # vars_prompt does not expand variables defined in inventory. (ansible 2.6.2)
    # https://github.com/ansible/ansible/issues/32723 (possible related issue)
    - pause:
        prompt: >
          Are you sure you want to run performance tests
          for {{ device_node_name }} on {{ inventory_hostname }} (yes/no)?
        echo: yes
      register: test_device_res
      failed_when: test_device_res.user_input not in yeses

- name: install required programs
  hosts: all
  any_errors_fatal: true
  tags: [ 'always' ]
  tasks:
    - name: install dependent apt packages (remote)
      become: yes
      apt:
        autoclean: yes
        install_recommends: no
        name:
          - libaio-dev
          - build-essential
          - hdparm
        state: present
        update_cache: yes
    - name: install dependent apt packages (local)
      become: yes
      run_once: yes
      local_action:
        module: apt
        autoclean: yes
        install_recommends: no
        name:
          - python3-numpy
        state: present
        update_cache: yes
    - name: ensure the presence of workdir {{ workdir }}
      file:
        path: "{{ workdir }}"
        state: directory
    - set_fact:
        fio_dir: "{{ workdir }}/fio-fio-{{ fio_version }}"
    - name: download fio-{{ fio_version }} source code
      unarchive:
        creates: "{{ fio_dir }}"
        dest: "{{ workdir }}"
        remote_src: yes
        src: https://codeload.github.com/axboe/fio/tar.gz/fio-{{ fio_version }}
    - name: build fio-{{ fio_version }} from source
      shell: ./configure && make -j2
      args:
        chdir: "{{ fio_dir }}"
        creates: "{{ fio_dir }}/fio"

- name: run performance tests
  hosts: all
  tags: [ 'always' ]
  vars:
    remote_data_dir: "{{ workdir }}/data"
    remote_job_files_dir: "{{ remote_data_dir }}/job_files"
    remote_output_dir: "{{ remote_data_dir }}/output_{{ role_path | basename }}"
    local_output_dir: "{{ inventory_dir }}/analysis/data/{{ inventory_hostname }}/output_{{ role_path | basename }}"
    output_format: json+
    output_file_suffix: json
    pre_conditioning_job_filename: pre-conditioning.fio
    pre_conditioning_job_file: "{{ remote_job_files_dir }}/{{ pre_conditioning_job_filename }}"
  pre_tasks:
    - set_fact:
        run_perf_tests: "{{ ansible_run_tags | intersect(role_names) }}"
    - debug:
        msg: >
          Please specify at least one of performance tests
          {{ role_names }} using '--tags'
      when: run_perf_tests | length == 0
      failed_when: run_perf_tests | length == 0

    - name: load global variables for performance test specification
      include_vars:
        file: "{{ test_spec }}.yml"
    - name: update write caching
      become: yes
      command: hdparm -W{{ write_caching }} {{ device_node_name }}
    - name: get size of {{ device_node_name }} in bytes
      become: yes
      command: blockdev --getsize64 {{ device_node_name }}
      register: comm_res
    - set_fact:
        device_size: "{{ comm_res.stdout }}"
    - name: check and kill remnant pre-conditioning process
      become: yes
      shell: pkill -KILL -u "$(id -u)" -f 'fio\s+{{ pre_conditioning_job_file }}'
      ignore_errors: yes
    - name: ensure the presence of job files dir {{ remote_job_files_dir }}
      file:
        path: "{{ remote_job_files_dir }}"
        state: directory
  roles:
    - role: throughput
      when: role_path | basename in run_perf_tests
    - role: iops
      when: role_path | basename in run_perf_tests
...
